language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  global:
    - setup=basic
    - coverage=no

before_script:
  - travis_retry composer self-update
  - composer config discard-changes true
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --prefer-source --no-interaction; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-source --no-interaction --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-source --no-interaction --prefer-lowest --prefer-stable; fi
  - if [[ $setup = 'coveralls' ]]; then travis_retry composer require "psr/log=1.0.0" "satooshi/php-coveralls=~0.6" "symfony/yaml=~2.0" --prefer-source --no-interaction --dev; fi

script:
  - ./vendor/bin/phpspec run

matrix:
  include:
    - php: 5.5
      env: setup=lowest
    - php: 5.5
      env: setup=stable
  allow_failures:
    - env: setup=stable
    - php: 7.0
  fast_finish: true
